### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [RafalPatro/magicnumbers#1]
Nie widać obiektowych praktyk za wielu. Jakiś pomysł co z tym zrobić?
Czy masz jakiś pomysł jak zastąpić System.exit czym innym?

**Comment by LIttleAncientForestKami** [comment]
Dodatkowo, zerknij proszę na zapisaną sesję działania programu (format to linia z nazwą pliku, linia co mówi program file i linie pochodzące z Twojego programu odpalonego z tym plikiem podanym jako parametr):

```
[tammo@lafk-T470 src]$ ./magNum.sh                                                                          [INSERT]
../../test_ANSIrtf.rtf
../../test_ANSIrtf.rtf: Rich Text Format data, version 1, ANSI
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_ASCIItxt.jpg
../../test_ASCIItxt.jpg: ASCII text
Its  file
../../test_ASCIItxt_noExt
../../test_ASCIItxt_noExt: ASCII text
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_ASCIItxt.png
../../test_ASCIItxt.png: ASCII text
Its  file
../../test_ASCIItxt.txt
../../test_ASCIItxt.txt: ASCII text
Its txt file
../../test_docx.docx
../../test_docx.docx: Microsoft Word 2007+
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_empty.jpeg
../../test_empty.jpeg: empty
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_empty.pdf
../../test_empty.pdf: empty
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_gif89a.gif
../../test_gif89a.gif: GIF image data, version 89a, 153 x 200
Its gif file
../../test_jpegJFIF.jpg
../../test_jpegJFIF.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, baseline, precision 8, 153x200, frames 3
Its jpg file
../../test_pdf.pdf
../../test_pdf.pdf: PDF document, version 1.6
Exception in thread "main" java.util.NoSuchElementException: This extension is not supported
	at pl.patro.Main.main(Main.java:44)
../../test_png.png
../../test_png.png: PNG image data, 153 x 200, 8-bit/color RGB, non-interlaced
Its png file
../../test_png.txt
../../test_png.txt: PNG image data, 153 x 200, 8-bit/color RGB, non-interlaced
Extension is txt, while actually it's a png
```

**Comment by RafalPatro** [comment]
Można stworzyć interfejs z definicjami metod wymaganych do poprawnego działania algorytmu

Następnie klasa FileCodes może zaimplementować dany interfejs, metody będą wykonywać działania bezpośrednio na obiektach. 

Zyskamy również dodatkową warstwę pozwalającą nam oddzielić szczegóły implementacyjne,
dzięki temu w metodzie main będzie możliwość użycia obiektu dowolnej klasy implementującej dany interfejs. 

Zamiast System.exit można łapać wyjątki w metodzie main oraz kończyć program za pomocą return.
